package com.example.merchandisecontrolsplitview.ui.screens

import android.widget.Toast
import androidx.activity.compose.BackHandler
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.KeyboardActions
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.CameraAlt
import androidx.compose.material.icons.filled.Search
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.focus.FocusRequester
import androidx.compose.ui.focus.focusRequester
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.input.ImeAction
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.unit.dp
import androidx.compose.ui.text.TextRange
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.TextFieldValue
import com.journeyapps.barcodescanner.ScanContract
import com.journeyapps.barcodescanner.ScanOptions
import com.journeyapps.barcodescanner.ScanOptions.ALL_CODE_TYPES
import java.time.LocalDateTime
import java.time.format.DateTimeFormatter
import com.example.merchandisecontrolsplitview.PortraitCaptureActivity // se hai questa classe nel tuo package
import com.example.merchandisecontrolsplitview.viewmodel.ExcelViewModel
import com.example.merchandisecontrolsplitview.ui.components.ZoomableExcelGrid
import kotlinx.coroutines.launch
import androidx.compose.material.icons.filled.Calculate
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.TextUnit
import com.example.merchandisecontrolsplitview.R
import com.example.merchandisecontrolsplitview.util.getLocalizedHeader
import java.util.Locale


/**
 * Schermata per visualizzare e modificare la griglia generata.
 * Ogni modifica viene salvata nella cronologia corrente.
 */
@Composable
fun GeneratedScreen(
    viewModel: ExcelViewModel,
    onBackToStart: () -> Unit
) {
    val context = LocalContext.current
    val scope = rememberCoroutineScope()

    // ViewModel state
    val excelData by remember { derivedStateOf { viewModel.excelData } }
    val selectedColumns by remember { derivedStateOf { viewModel.selectedColumns } }
    val editableValues by remember { derivedStateOf { viewModel.editableValues } }
    val completeStates by remember { derivedStateOf { viewModel.completeStates } }
    val generated by viewModel.generated

    // Dialog & search state
    var showSearchDialog by remember { mutableStateOf(false) }
    var searchText by remember { mutableStateOf("") }
    var searchMatches by remember { mutableStateOf(setOf<Pair<Int, Int>>()) }
    var showInfoDialog by remember { mutableStateOf(false) }
    var infoRowIndex by remember { mutableIntStateOf(-1) }
    var infoDialogFocusField by remember { mutableIntStateOf(0) }

    var showCalcDialog by remember { mutableStateOf(false) }
    var calcInput by remember { mutableStateOf("") }
    var calcResult by remember { mutableStateOf("") }
    var calcRowIndex by remember { mutableIntStateOf(-1) }

    BackHandler { onBackToStart() }

    // Scanner
    val scanLauncher = rememberLauncherForActivityResult(ScanContract()) { result ->
        result?.contents?.let { code ->
            val matches = excelData.flatMapIndexed { r, row -> row.mapIndexedNotNull { c, v -> if (v == code) r to c else null } }.toSet()
            if (matches.isNotEmpty()) {
                searchMatches = matches
                val (r, c) = matches.first()
                infoRowIndex = r
                infoDialogFocusField = if (c >= excelData[0].size - 2) c - (excelData[0].size - 2) else 0
                showInfoDialog = true
                showSearchDialog = false
            } else {
                Toast.makeText(context, context.getString(R.string.not_found), Toast.LENGTH_SHORT).show()
            }
        } ?: Toast.makeText(context, context.getString(R.string.no_scanner_result), Toast.LENGTH_SHORT).show()
    }

    val saveLauncher = rememberLauncherForActivityResult(
        ActivityResultContracts.CreateDocument("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
    ) { uri ->
        uri?.let { targetUri ->
            scope.launch {                      // 2) lancio la coroutine qui
                viewModel.saveFileSuspend(context, targetUri)
                onBackToStart()                 // 3) navigo indietro **dopo** il salvataggio
            }
        }
    }

    // Manual search
    fun performSearch() {
        val matches = excelData.flatMapIndexed { r, row ->
            row.mapIndexedNotNull { c, v -> if (v == searchText) r to c else null }
        }.toSet()
        if (matches.isNotEmpty()) {
            searchMatches = matches
            val (r, c) = matches.first()
            infoRowIndex = r
            infoDialogFocusField = if (c >= excelData[0].size - 2) c - (excelData[0].size - 2) else 0
            showInfoDialog = true
            showSearchDialog = false
        } else {
            searchText = ""
            Toast.makeText(context, context.getString(R.string.not_found), Toast.LENGTH_SHORT).show()
        }
    }

    // UI
    Box(Modifier.fillMaxSize()) {
        Column(Modifier.fillMaxSize()) {
            // Salva file
            if (excelData.isNotEmpty() && generated) {
                Button(
                    onClick = {
                        val stamp = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd_HH:mm"))
                        val name = "$stamp.xlsx"
                        saveLauncher.launch(name)
                    },
                    modifier = Modifier.fillMaxWidth().padding(16.dp)
                ) { Text(stringResource(R.string.save_file)) }
            }

            if (excelData.isNotEmpty()) {
                val localizedHeader = excelData[0].map { getLocalizedHeader(context, it) }
                val localizedData = listOf(localizedHeader) + excelData.drop(1)
                ZoomableExcelGrid(
                    data = localizedData,
                    cellWidth = 120.dp,
                    cellHeight = 48.dp,
                    selectedColumns = selectedColumns,
                    editableValues = editableValues,
                    completeStates = completeStates,
                    searchMatches = searchMatches,
                    generated = true,
                    editMode = false,
                    onCompleteToggle = { row ->
                        completeStates[row] = !completeStates[row]
                        viewModel.updateHistoryEntry() // aggiorna stato nella cronologia
                    },
                    onCellEditRequest = { _, _ -> },
                    onQuantityCellClick = { r ->
                        infoRowIndex = r; infoDialogFocusField = 0; showInfoDialog = true
                    },
                    onPriceCellClick = { r ->
                        infoRowIndex = r; infoDialogFocusField = 1; showInfoDialog = true
                    },
                    onRowCellClick = { r ->
                        infoRowIndex = r; infoDialogFocusField = 0; showInfoDialog = true
                    }
                )
            }
        }

        // FAB Scanner e Cerca
        if (excelData.isNotEmpty() && generated) {
            Column(
                Modifier.align(Alignment.BottomEnd).padding(end = 16.dp, bottom = 88.dp),
                verticalArrangement = Arrangement.spacedBy(16.dp),
                horizontalAlignment = Alignment.End
            ) {
                FloatingActionButton(onClick = {
                    val opts = ScanOptions().apply {
                        setDesiredBarcodeFormats(ALL_CODE_TYPES)
                        setCaptureActivity(PortraitCaptureActivity::class.java)
                        setOrientationLocked(true)
                        setBeepEnabled(true)
                        setPrompt(context.getString(R.string.scan_prompt))
                    }
                    scanLauncher.launch(opts)
                }) { Icon(Icons.Filled.CameraAlt, contentDescription = R.string.scan_icon_desc.toString()) }

                FloatingActionButton(onClick = { searchText = ""; showSearchDialog = true }) {
                    Icon(Icons.Filled.Search, contentDescription = R.string.search_icon_desc.toString())
                }
            }
        }

        // Dialog di ricerca
        if (showSearchDialog) {
            AlertDialog(
                onDismissRequest = {},
                title = { Text(stringResource(R.string.search_number)) },
                text = {
                    Column {
                        Button(onClick = { scanLauncher.launch(
                            ScanOptions().apply {
                                setDesiredBarcodeFormats(ALL_CODE_TYPES)
                                setCaptureActivity(PortraitCaptureActivity::class.java)
                                setOrientationLocked(true)
                                setBeepEnabled(true)
                                setPrompt(context.getString(R.string.scan_prompt))
                            }
                        )}, Modifier.fillMaxWidth().padding(bottom = 8.dp)) {
                            Icon(Icons.Filled.CameraAlt, contentDescription = null)
                            Spacer(Modifier.width(8.dp))
                            Text(stringResource(R.string.scanner))
                        }
                        TextField(
                            value = searchText,
                            onValueChange = { searchText = it },
                            label = { Text(stringResource(R.string.insert_number)) },
                            singleLine = true,
                            keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number, imeAction = ImeAction.Search),
                            keyboardActions = KeyboardActions(onSearch = { performSearch() }),
                            modifier = Modifier.fillMaxWidth()
                        )
                    }
                },
                confirmButton = { TextButton(onClick = { performSearch() }) {Text(stringResource(R.string.search_number)) } },
                dismissButton = { TextButton(onClick = { showSearchDialog = false }) { Text(stringResource(R.string.clear)) } }
            )
        }

        // Info dialog (autocount/newRetailPrice)
        if (showInfoDialog && infoRowIndex in excelData.indices) {

            val header = excelData.first()
            val row = excelData[infoRowIndex]
            val qtyReq = remember { FocusRequester() }
            val priceReq = remember { FocusRequester() }
            LaunchedEffect(showInfoDialog, infoDialogFocusField) {
                if (infoDialogFocusField == 0) qtyReq.requestFocus() else priceReq.requestFocus()
            }
            AlertDialog(
                onDismissRequest = {showInfoDialog = false},
                title = { Text(stringResource(R.string.row_info)) },
                text = {
                    Column(Modifier.verticalScroll(rememberScrollState()).fillMaxWidth()) {
                        header.forEachIndexed { ci, name ->
                            // BLOCCO CORRETTO CON 'when'
                            when (name) {
                                "autocount", "newRetailPrice" -> {
                                    val idx = if (name == "autocount") 0 else 1
                                    val req = if (idx == 0) qtyReq else priceReq
                                    var tf by remember { mutableStateOf(TextFieldValue(editableValues[infoRowIndex][idx].value, TextRange(editableValues[infoRowIndex][idx].value.length))) }
                                    Row(Modifier.fillMaxWidth().padding(vertical = 4.dp), verticalAlignment = Alignment.CenterVertically) {
                                        Text(getLocalizedHeader(context, name) + ":", Modifier.weight(1f), style = MaterialTheme.typography.bodyMedium)
                                        TextField(
                                            value = tf,
                                            onValueChange = { nv -> tf = nv; editableValues[infoRowIndex][idx].value = nv.text; viewModel.updateHistoryEntry() },
                                            singleLine = true,
                                            keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number, imeAction = if (idx == 0) ImeAction.Next else ImeAction.Done),
                                            keyboardActions = KeyboardActions(onNext = { if (idx == 0) priceReq.requestFocus() }, onDone = { completeStates[infoRowIndex] = !completeStates[infoRowIndex]; viewModel.updateHistoryEntry(); showInfoDialog = false }),
                                            modifier = Modifier.weight(1f).height(48.dp).border(1.dp, Color.Gray, RoundedCornerShape(4.dp)).clip(RoundedCornerShape(4.dp)).focusRequester(req)
                                        )
                                    }
                                }
                                "purchasePrice" -> {
                                    val idx = header.indexOf("purchasePrice")
                                    val value = row.getOrNull(idx) ?: ""
                                    Row(Modifier.fillMaxWidth().padding(vertical = 4.dp), verticalAlignment = Alignment.CenterVertically) {
                                        Text(getLocalizedHeader(context, name) + ":", Modifier.weight(1f), style = MaterialTheme.typography.bodyMedium)
                                        Text(
                                            value,
                                            Modifier
                                                .weight(1f)
                                                .background(
                                                    MaterialTheme.colorScheme.surfaceVariant,
                                                    RoundedCornerShape(4.dp)
                                                )
                                                .padding(horizontal = 8.dp, vertical = 2.dp),
                                            style = MaterialTheme.typography.bodyMedium.copy(
                                                color = MaterialTheme.colorScheme.primary,
                                                fontWeight = FontWeight.Bold
                                            )
                                        )
                                        IconButton(
                                            onClick = {
                                                calcInput = value
                                                calcResult = value
                                                calcRowIndex = infoRowIndex
                                                showCalcDialog = true
                                            }
                                        ) {
                                            Icon(Icons.Filled.Calculate, contentDescription = "Calcola nuovo valore")
                                        }
                                    }
                                }
                                else -> {
                                    Row(Modifier.fillMaxWidth().padding(vertical = 4.dp)) {
                                        Text(getLocalizedHeader(context, name) + ":", Modifier.weight(1f), style = MaterialTheme.typography.bodyMedium)
                                        val value = row.getOrNull(ci) ?: ""
                                        if (name == "oldPurchasePrice" || name == "oldRetailPrice") {
                                            Text(
                                                value,
                                                Modifier.weight(1f)
                                                    .background(
                                                        if (value.isNotBlank()) MaterialTheme.colorScheme.primary.copy(alpha = 0.10f) else Color.Transparent,
                                                        RoundedCornerShape(4.dp)
                                                    )
                                                    .padding(horizontal = 8.dp, vertical = 2.dp),
                                                style = MaterialTheme.typography.bodyMedium.copy(
                                                    color = if (value.isNotBlank()) MaterialTheme.colorScheme.primary else MaterialTheme.colorScheme.onSurface,
                                                    fontWeight = if (value.isNotBlank()) FontWeight.Bold else FontWeight.Normal
                                                )
                                            )
                                        } else {
                                            Text(
                                                value,
                                                Modifier.weight(1f),
                                                style = MaterialTheme.typography.bodyMedium
                                            )
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                confirmButton = { TextButton(onClick = { completeStates[infoRowIndex] = !completeStates[infoRowIndex]; viewModel.updateHistoryEntry(); showInfoDialog = false }) { Text(getLocalizedHeader(context, "complete")) } },
                dismissButton = { TextButton(onClick = { showInfoDialog = false }) { Text(stringResource(R.string.confirm)) } }
            )
        }

        if (showCalcDialog && calcRowIndex == infoRowIndex) {
            CalculatorDialog(
                value = calcInput,
                onValueChange = { calcInput = it },
                onResult = { res ->
                    // Aggiorna la cella della purchasePrice SOLO per questa riga
                    val idx = viewModel.excelData.first().indexOf("purchasePrice")
                    if (idx > -1) {
                        viewModel.excelData[infoRowIndex] =
                            viewModel.excelData[infoRowIndex].toMutableList().also { it[idx] = formatDecimal(res) }
                        viewModel.updateHistoryEntry()
                    }
                },
                onDismiss = { showCalcDialog = false }
            )
        }
    }
}


fun evalSimpleExpr(expr: String): Double {
    val clean = expr.replace(",", ".").replace(" ", "")
    return object : Any() {
        var pos = -1; var ch = 0
        fun nextChar() { ch = if (++pos < clean.length) clean[pos].code else -1 }
        fun eat(charToEat: Int): Boolean {
            while (ch == ' '.code) nextChar()
            if (ch == charToEat) { nextChar(); return true }
            return false
        }
        fun parse(): Double {
            nextChar()
            val x = parseExpression()
            if (pos < clean.length) throw RuntimeException("Unexpected: " + clean[pos])
            return x
        }
        fun parseExpression(): Double {
            var x = parseTerm()
            while (true) {
                when {
                    eat('+'.code) -> x += parseTerm()
                    eat('-'.code) -> x -= parseTerm()
                    else -> return x
                }
            }
        }
        fun parseTerm(): Double {
            var x = parseFactor()
            while (true) {
                when {
                    eat('*'.code) -> x *= parseFactor()
                    eat('/'.code) -> x /= parseFactor()
                    else -> return x
                }
            }
        }
        fun parseFactor(): Double {
            if (eat('+'.code)) return parseFactor()
            if (eat('-'.code)) return -parseFactor()
            val x: Double
            val startPos = pos
            if (eat('('.code)) {
                x = parseExpression()
                eat(')'.code)
            } else if ((ch in '0'.code..'9'.code) || ch == '.'.code) {
                while ((ch in '0'.code..'9'.code) || ch == '.'.code) nextChar()
                x = clean.substring(startPos, pos).toDouble()
            } else throw RuntimeException("Unexpected: " + ch.toChar())
            return x
        }
    }.parse()
}

@Composable
fun CalculatorDialog(
    value: String,
    onValueChange: (String) -> Unit,
    onResult: (String) -> Unit,
    onDismiss: () -> Unit
) {
    var input by remember { mutableStateOf(value) }
    var result by remember { mutableStateOf("") }

    fun updateResult(str: String) {
        result = try {
            if (str.trim().endsWith("=")) {
                evalSimpleExpr(str.trim().removeSuffix("=")).toString()
            } else ""
        } catch (e: Exception) { "Errore" }
    }

    AlertDialog(
        onDismissRequest = onDismiss,
        title = { Text(stringResource(R.string.calc_title)) },
        text = {
            Column(
                horizontalAlignment = Alignment.CenterHorizontally,
                modifier = Modifier.fillMaxWidth()
            ) {
                OutlinedTextField(
                    value = input,
                    onValueChange = {
                        input = it
                        updateResult(it)
                        onValueChange(it)
                    },
                    label = { Text(stringResource(R.string.calc_label)) },
                    singleLine = true,
                    readOnly = true, // SOLO tramite tastiera custom
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(bottom = 6.dp)
                )
                // --- RISULTATO appena sotto il campo input ---
                Text(
                    text = if (result.isNotBlank() && result != "Errore") {
                        stringResource(R.string.result) + " ${result.toDoubleOrNull()?.let { String.format(Locale.US, "%.2f", it) } ?: result}"
                    } else stringResource(R.string.result),
                    style = MaterialTheme.typography.titleMedium,
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(bottom = 24.dp)
                        .background(
                            MaterialTheme.colorScheme.primary.copy(alpha = 0.04f),
                            RoundedCornerShape(6.dp)
                        )
                        .padding(8.dp)
                )
                // --- PIÙ SPAZIO SOPRA LA TASTIERA ---
                Spacer(Modifier.height(8.dp))
                // --- TASTIERA con tasti più GRANDI e distanziati ---
                CalculatorKeyboard(
                    onKey = { key ->
                        when (key) {
                            "C" -> { input = ""; result = ""; onValueChange("") }
                            "<" -> {
                                if (input.isNotEmpty()) {
                                    input = input.dropLast(1)
                                    updateResult(input)
                                    onValueChange(input)
                                }
                            }
                            "=" -> {
                                if (input.isNotBlank()) {
                                    val toEval = if (input.trim().endsWith("=")) input.trim() else input.trim() + "="
                                    updateResult(toEval)
                                    input = toEval
                                    onValueChange(toEval)
                                }
                            }
                            else -> {
                                input += key
                                updateResult(input)
                                onValueChange(input)
                            }
                        }
                    },
                    buttonSize = 68.dp,    // <--- PIÙ GRANDE!
                    buttonFontSize = MaterialTheme.typography.headlineSmall.fontSize
                )
            }
        },
        confirmButton = {
            TextButton(onClick = {
                if (result.isNotBlank() && result != "Errore") {
                    onResult(result)
                } else {
                    onResult(input)
                }
                onDismiss()
            }) { Text(stringResource(R.string.ok)) }
        },
        dismissButton = {
            TextButton(onClick = { onDismiss() }) { Text(stringResource(R.string.cancel)) }
        }
    )
}

@Composable
fun CalculatorKeyboard(
    onKey: (String) -> Unit,
    buttonSize: Dp = 56.dp,
    buttonFontSize: TextUnit = MaterialTheme.typography.titleLarge.fontSize
) {
    val buttons = listOf(
        listOf("C", "<"),
        listOf("+", "7", "8", "9"),
        listOf("-", "4", "5", "6"),
        listOf("*", "1", "2", "3"),
        listOf("/", ".", "0", "="),

    )
    Column(
        Modifier.fillMaxWidth(),
        horizontalAlignment = Alignment.CenterHorizontally
    ) {
        buttons.forEach { row ->
            Row(
                Modifier
                    .fillMaxWidth()
                    .padding(vertical = 2.dp), // più spazio tra righe
                horizontalArrangement = Arrangement.SpaceEvenly
            ) {
                row.forEach { label ->
                    Button(
                        onClick = { onKey(label) },
                        modifier = Modifier
                            .size(buttonSize)
                            .padding(2.dp),
                        shape = RoundedCornerShape(18.dp)
                    ) {
                        Text(label, fontWeight = FontWeight.Bold, fontSize = buttonFontSize)
                    }
                }
                // Per le righe più corte, aggiungi spaziatori
                repeat(4 - row.size) { Spacer(Modifier.size(buttonSize)) }
            }
        }
    }
}

fun formatDecimal(num: Double, digits: Int = 2): String =
    String.format(Locale.US, "%.${digits}f", num)

fun formatDecimal(num: String, digits: Int = 2): String =
    num.toDoubleOrNull()?.let { formatDecimal(it, digits) } ?: num