package com.example.merchandisecontrolsplitview.ui.screens

import android.widget.Toast
import androidx.activity.compose.BackHandler
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.KeyboardActions
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.CameraAlt
import androidx.compose.material.icons.filled.Search
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.focus.FocusRequester
import androidx.compose.ui.focus.focusRequester
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.input.ImeAction
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.unit.dp
import androidx.compose.ui.text.TextRange
import androidx.compose.ui.text.input.TextFieldValue
import com.journeyapps.barcodescanner.ScanContract
import com.journeyapps.barcodescanner.ScanOptions
import com.journeyapps.barcodescanner.ScanOptions.ALL_CODE_TYPES
import java.time.LocalDateTime
import java.time.format.DateTimeFormatter
import com.example.merchandisecontrolsplitview.PortraitCaptureActivity // se hai questa classe nel tuo package
import com.example.merchandisecontrolsplitview.viewmodel.ExcelViewModel
import com.example.merchandisecontrolsplitview.ui.components.ZoomableExcelGrid
import kotlinx.coroutines.launch


/**
 * Schermata per visualizzare e modificare la griglia generata.
 * Ogni modifica viene salvata nella cronologia corrente.
 */
@Composable
fun GeneratedScreen(
    viewModel: ExcelViewModel,
    onBackToStart: () -> Unit
) {
    val context = LocalContext.current
    val scope = rememberCoroutineScope()

    // ViewModel state
    val excelData by remember { derivedStateOf { viewModel.excelData } }
    val selectedColumns by remember { derivedStateOf { viewModel.selectedColumns } }
    val editableValues by remember { derivedStateOf { viewModel.editableValues } }
    val completeStates by remember { derivedStateOf { viewModel.completeStates } }
    val generated by viewModel.generated

    // Dialog & search state
    var showSearchDialog by remember { mutableStateOf(false) }
    var searchText by remember { mutableStateOf("") }
    var searchMatches by remember { mutableStateOf(setOf<Pair<Int, Int>>()) }
    var showInfoDialog by remember { mutableStateOf(false) }
    var infoRowIndex by remember { mutableIntStateOf(-1) }
    var infoDialogFocusField by remember { mutableIntStateOf(0) }

    // Scanner
    val scanLauncher = rememberLauncherForActivityResult(ScanContract()) { result ->
        result?.contents?.let { code ->
            val matches = excelData.flatMapIndexed { r, row -> row.mapIndexedNotNull { c, v -> if (v == code) r to c else null } }.toSet()
            if (matches.isNotEmpty()) {
                searchMatches = matches
                val (r, c) = matches.first()
                infoRowIndex = r
                infoDialogFocusField = if (c >= excelData[0].size - 2) c - (excelData[0].size - 2) else 0
                showInfoDialog = true
                showSearchDialog = false
            } else {
                Toast.makeText(context, "Numero non trovato", Toast.LENGTH_SHORT).show()
            }
        } ?: Toast.makeText(context, "Nessun risultato dallo scanner", Toast.LENGTH_SHORT).show()
    }

    val saveLauncher = rememberLauncherForActivityResult(
        ActivityResultContracts.CreateDocument("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
    ) { uri ->
        uri?.let { targetUri ->
            scope.launch {                      // 2) lancio la coroutine qui
                viewModel.saveFileSuspend(context, targetUri)
                onBackToStart()                 // 3) navigo indietro **dopo** il salvataggio
            }
        }
    }

    // Override back
    BackHandler { onBackToStart() }

    // Manual search
    fun performSearch() {
        val matches = excelData.flatMapIndexed { r, row ->
            row.mapIndexedNotNull { c, v -> if (v == searchText) r to c else null }
        }.toSet()
        if (matches.isNotEmpty()) {
            searchMatches = matches
            val (r, c) = matches.first()
            infoRowIndex = r
            infoDialogFocusField = if (c >= excelData[0].size - 2) c - (excelData[0].size - 2) else 0
            showInfoDialog = true
            showSearchDialog = false
        } else {
            searchText = ""
            Toast.makeText(context, "Numero non trovato", Toast.LENGTH_SHORT).show()
        }
    }

    // UI
    Box(Modifier.fillMaxSize()) {
        Column(Modifier.fillMaxSize()) {
            // Salva file
            if (excelData.isNotEmpty() && generated) {
                Button(
                    onClick = {
                        val stamp = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd_HH:mm"))
                        val name = "$stamp.xlsx"
                        saveLauncher.launch(name)
                    },
                    modifier = Modifier.fillMaxWidth().padding(16.dp)
                ) { Text("Salva file") }
            }

            // Griglia
            ZoomableExcelGrid(
                data = excelData,
                cellWidth = 120.dp,
                cellHeight = 48.dp,
                selectedColumns = selectedColumns,
                editableValues = editableValues,
                completeStates = completeStates,
                searchMatches = searchMatches,
                generated = true,
                editMode = false,
                onCompleteToggle = { row ->
                    completeStates[row] = !completeStates[row]
                    viewModel.updateHistoryEntry() // aggiorna stato nella cronologia
                },
                onCellEditRequest = { _, _ -> },
                onQuantityCellClick = { r -> infoRowIndex = r; infoDialogFocusField = 0; showInfoDialog = true },
                onPriceCellClick = { r -> infoRowIndex = r; infoDialogFocusField = 1; showInfoDialog = true },
                onRowCellClick = { r -> infoRowIndex = r; infoDialogFocusField = 0; showInfoDialog = true }
            )
        }

        // FAB Scanner e Cerca
        if (excelData.isNotEmpty() && generated) {
            Column(
                Modifier.align(Alignment.BottomEnd).padding(end = 16.dp, bottom = 88.dp),
                verticalArrangement = Arrangement.spacedBy(16.dp),
                horizontalAlignment = Alignment.End
            ) {
                FloatingActionButton(onClick = {
                    val opts = ScanOptions().apply {
                        setDesiredBarcodeFormats(ALL_CODE_TYPES)
                        setCaptureActivity(PortraitCaptureActivity::class.java)
                        setOrientationLocked(true)
                        setBeepEnabled(true)
                        setPrompt("Inquadra un barcode")
                    }
                    scanLauncher.launch(opts)
                }) { Icon(Icons.Filled.CameraAlt, contentDescription = "Scannerizza codice") }

                FloatingActionButton(onClick = { searchText = ""; showSearchDialog = true }) {
                    Icon(Icons.Filled.Search, contentDescription = "Cerca numero")
                }
            }
        }

        // Dialog di ricerca
        if (showSearchDialog) {
            AlertDialog(
                onDismissRequest = {},
                title = { Text("Cerca numero") },
                text = {
                    Column {
                        Button(onClick = { scanLauncher.launch(
                            ScanOptions().apply {
                                setDesiredBarcodeFormats(ALL_CODE_TYPES)
                                setCaptureActivity(PortraitCaptureActivity::class.java)
                                setOrientationLocked(true)
                                setBeepEnabled(true)
                                setPrompt("Inquadra un barcode")
                            }
                        )}, Modifier.fillMaxWidth().padding(bottom = 8.dp)) {
                            Icon(Icons.Filled.CameraAlt, contentDescription = null)
                            Spacer(Modifier.width(8.dp))
                            Text("Scanner")
                        }
                        TextField(
                            value = searchText,
                            onValueChange = { searchText = it },
                            label = { Text("Inserisci numero") },
                            singleLine = true,
                            keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number, imeAction = ImeAction.Search),
                            keyboardActions = KeyboardActions(onSearch = { performSearch() }),
                            modifier = Modifier.fillMaxWidth()
                        )
                    }
                },
                confirmButton = { TextButton(onClick = { performSearch() }) { Text("Cerca") } },
                dismissButton = { TextButton(onClick = { showSearchDialog = false }) { Text("Cancella") } }
            )
        }

        // Info dialog (quantità/prezzo)
        if (showInfoDialog && infoRowIndex in excelData.indices) {
            val header = excelData.first()
            val row = excelData[infoRowIndex]
            val qtyReq = remember { FocusRequester() }
            val priceReq = remember { FocusRequester() }
            LaunchedEffect(showInfoDialog, infoDialogFocusField) {
                if (infoDialogFocusField == 0) qtyReq.requestFocus() else priceReq.requestFocus()
            }
            AlertDialog(
                onDismissRequest = {},
                title = { Text("Informazioni riga") },
                text = {
                    Column(Modifier.verticalScroll(rememberScrollState()).fillMaxWidth()) {
                        header.forEachIndexed { ci, name ->
                            if (name == "Quantità" || name == "Prezzo") {
                                val idx = if (name == "Quantità") 0 else 1
                                val req = if (idx == 0) qtyReq else priceReq
                                var tf by remember { mutableStateOf(TextFieldValue(editableValues[infoRowIndex][idx].value, TextRange(editableValues[infoRowIndex][idx].value.length))) }
                                Row(Modifier.fillMaxWidth().padding(vertical = 4.dp), verticalAlignment = Alignment.CenterVertically) {
                                    Text("$name:", Modifier.weight(1f), style = MaterialTheme.typography.bodyMedium)
                                    TextField(
                                        value = tf,
                                        onValueChange = { nv -> tf = nv; editableValues[infoRowIndex][idx].value = nv.text; viewModel.updateHistoryEntry() },
                                        singleLine = true,
                                        keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number, imeAction = if (idx == 0) ImeAction.Next else ImeAction.Done),
                                        keyboardActions = KeyboardActions(onNext = { if (idx == 0) priceReq.requestFocus() }, onDone = { completeStates[infoRowIndex] = !completeStates[infoRowIndex]; viewModel.updateHistoryEntry(); showInfoDialog = false }),
                                        modifier = Modifier.weight(1f).height(48.dp).border(1.dp, Color.Gray, RoundedCornerShape(4.dp)).clip(RoundedCornerShape(4.dp)).focusRequester(req)
                                    )
                                }
                            } else {
                                Row(Modifier.fillMaxWidth().padding(vertical = 4.dp)) {
                                    Text("$name:", Modifier.weight(1f), style = MaterialTheme.typography.bodyMedium)
                                    Text(row.getOrNull(ci) ?: "", Modifier.weight(1f), style = MaterialTheme.typography.bodyMedium)
                                }
                            }
                        }
                    }
                },
                confirmButton = { TextButton(onClick = { completeStates[infoRowIndex] = !completeStates[infoRowIndex]; viewModel.updateHistoryEntry(); showInfoDialog = false }) { Text("Completo") } },
                dismissButton = { TextButton(onClick = { showInfoDialog = false }) { Text("Conferma") } }
            )
        }
    }
}
