package com.example.merchandisecontrolsplitview.ui.screens

import android.widget.Toast
import androidx.activity.compose.BackHandler
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.focusable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.KeyboardActions
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.CameraAlt
import androidx.compose.material.icons.filled.Search
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.focus.FocusRequester
import androidx.compose.ui.focus.focusRequester
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.input.ImeAction
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.unit.dp
import androidx.compose.ui.text.TextRange
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.TextFieldValue
import com.journeyapps.barcodescanner.ScanContract
import com.journeyapps.barcodescanner.ScanOptions
import com.journeyapps.barcodescanner.ScanOptions.ALL_CODE_TYPES
import com.example.merchandisecontrolsplitview.PortraitCaptureActivity // se hai questa classe nel tuo package
import com.example.merchandisecontrolsplitview.viewmodel.ExcelViewModel
import com.example.merchandisecontrolsplitview.ui.components.ZoomableExcelGrid
import kotlinx.coroutines.launch
import androidx.compose.material.icons.filled.Calculate
import androidx.compose.material.icons.filled.FileDownload
import androidx.compose.material.icons.filled.Sync
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.TextUnit
import androidx.navigation.NavHostController
import com.example.merchandisecontrolsplitview.R
import com.example.merchandisecontrolsplitview.util.getLocalizedHeader
import com.example.merchandisecontrolsplitview.viewmodel.DatabaseViewModel
import java.util.Locale
import com.example.merchandisecontrolsplitview.ui.navigation.Screen
import androidx.compose.foundation.interaction.MutableInteractionSource
import androidx.compose.material.icons.filled.CheckCircle
import androidx.compose.material.icons.filled.Error
import androidx.compose.material.icons.filled.Home
import androidx.compose.ui.graphics.vector.ImageVector


/**
 * Schermata per visualizzare e modificare la griglia generata.
 * Ogni modifica viene salvata nella cronologia corrente.
 */
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun GeneratedScreen(
    excelViewModel: ExcelViewModel,
    databaseViewModel: DatabaseViewModel,
    navController: NavHostController,
    onBackToStart: () -> Unit,
    entryId: String
) {
    val context = LocalContext.current
    val scope = rememberCoroutineScope()

    // ViewModel state
    val excelData by remember { derivedStateOf { excelViewModel.excelData } }
    val editableValues by remember { derivedStateOf { excelViewModel.editableValues } }
    val completeStates by remember { derivedStateOf { excelViewModel.completeStates } }
    val generated by excelViewModel.generated
    val (syncStatus, wasExported) = excelViewModel.currentEntryStatus.value
    val errorIndexes by excelViewModel.errorRowIndexes

    // Dialog & search state
    var showSearchDialog by remember { mutableStateOf(false) }
    var searchText by remember { mutableStateOf("") }
    var searchMatches by remember { mutableStateOf(setOf<Pair<Int, Int>>()) }
    var showInfoDialog by remember { mutableStateOf(false) }
    var infoRowIndex by remember { mutableIntStateOf(-1) }
    var infoDialogFocusField by remember { mutableIntStateOf(0) }
    var showCalcDialog by remember { mutableStateOf(false) }
    var calcInput by remember { mutableStateOf("") }
    var calcRowIndex by remember { mutableIntStateOf(-1) }
    var showRenameDialog by remember { mutableStateOf(false) }
    var renameText by remember { mutableStateOf(entryId) }
    var titleText by remember { mutableStateOf(entryId) }
    var showGenericCalcDialog by remember { mutableStateOf(false) }
    var showExitDialog by remember { mutableStateOf(false) }
    var onConfirmAction by remember { mutableStateOf({}) }

    var headerDialogIndex by remember { mutableStateOf<Int?>(null) }
    var showCustomHeaderDialog by remember { mutableStateOf(false) }
    var customHeader by remember { mutableStateOf("") }

    val possibleKeys = listOf(
        "barcode", "quantity", "purchasePrice", "retailPrice", "totalPrice",
        "productName", "secondProductName", "itemNumber", "supplier", "rowNumber",
        "discount", "discountedPrice"
    )

    BackHandler {
        onConfirmAction = { onBackToStart() }
        showExitDialog = true
    }

    val scanLauncher = rememberLauncherForActivityResult(ScanContract()) { result ->
        result?.contents?.let { code ->
            val matches = excelData.flatMapIndexed { r, row -> row.mapIndexedNotNull { c, v -> if (v == code) r to c else null } }.toSet()
            if (matches.isNotEmpty()) {
                searchMatches = matches
                val (r, c) = matches.first()
                infoRowIndex = r
                infoDialogFocusField = if (c >= excelData[0].size - 2) c - (excelData[0].size - 2) else 0
                showInfoDialog = true
                showSearchDialog = false
            } else {
                Toast.makeText(context, context.getString(R.string.not_found), Toast.LENGTH_SHORT).show()
            }
        } ?: Toast.makeText(context, context.getString(R.string.no_scanner_result), Toast.LENGTH_SHORT).show()
    }

    val saveLauncher = rememberLauncherForActivityResult(
        ActivityResultContracts.CreateDocument("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
    ) { uri ->
        uri?.let { targetUri ->
            scope.launch {
                excelViewModel.saveFileSuspend(context, uri)
                excelViewModel.markCurrentEntryAsExported()
                Toast.makeText(context, context.getString(R.string.file_exported_successfully), Toast.LENGTH_SHORT).show()
            }
        }
    }

    fun performSearch() {
        val matches = excelData.flatMapIndexed { r, row ->
            row.mapIndexedNotNull { c, v -> if (v == searchText) r to c else null }
        }.toSet()
        if (matches.isNotEmpty()) {
            searchMatches = matches
            val (r, c) = matches.first()
            infoRowIndex = r
            infoDialogFocusField = if (c >= excelData[0].size - 2) c - (excelData[0].size - 2) else 0
            showInfoDialog = true
            showSearchDialog = false
        } else {
            searchText = ""
            Toast.makeText(context, context.getString(R.string.not_found), Toast.LENGTH_SHORT).show()
        }
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = {
                    Text(
                        text = titleText,
                        modifier = Modifier
                            .clickable {
                                renameText = entryId
                                showRenameDialog = true
                            }
                    )
                },
                navigationIcon = {
                    IconButton(onClick = {
                        onConfirmAction = { onBackToStart() }
                        showExitDialog = true
                    }) {
                        Icon(Icons.AutoMirrored.Filled.ArrowBack, contentDescription = stringResource(R.string.back))
                    }
                },
                actions = {
                    if (excelData.isNotEmpty() && generated) {
                        // Pulsante Home (invariato)
                        IconButton(onClick = {
                            onConfirmAction = {
                                navController.navigate(Screen.FilePicker.route) {
                                    popUpTo(navController.graph.startDestinationId) {
                                        inclusive = true
                                    }
                                    launchSingleTop = true
                                }
                            }
                            showExitDialog = true
                        }) {
                            Icon(
                                Icons.Default.Home,
                                contentDescription = stringResource(R.string.go_to_home)
                            )
                        }

                        // --- PULSANTE SINCRONIZZA MODIFICATO ---
                        IconButton(onClick = {
                            // La logica qui dentro verrà modificata nel prossimo punto
                            excelViewModel.errorRowIndexes.value = emptySet()
                            val header = excelData.firstOrNull()
                            if (header == null) {
                                Toast.makeText(context, context.getString(R.string.invalid_data_for_analysis), Toast.LENGTH_SHORT).show()
                                return@IconButton
                            }

                            val dataRows = excelData.drop(1)
                            val gridDataForAnalysis = dataRows.mapIndexed { rowIndex, rowData ->
                                val actualRowIndex = rowIndex + 1

                                // Prendiamo i valori inseriti dall'utente, senza validarli qui.
                                // L'analizzatore gestirà stringhe vuote o non numeriche.
                                val finalQuantityStr = excelViewModel.editableValues.getOrNull(actualRowIndex)?.getOrNull(0)?.value ?: ""
                                val finalPriceStr = excelViewModel.editableValues.getOrNull(actualRowIndex)?.getOrNull(1)?.value ?: ""

                                // Creiamo la mappa dei dati per ogni riga
                                val map = header.mapIndexed { colIndex, headerKey ->
                                    headerKey to (rowData.getOrNull(colIndex) ?: "")
                                }.toMap().toMutableMap()

                                map["realQuantity"] = finalQuantityStr
                                map["retailPrice"] = finalPriceStr
                                map["supplier"] = excelViewModel.supplierName

                                map.toMap() // Ritorna sempre la mappa, anche se i valori sono vuoti o invalidi
                            }
                            // --- FINE LOGICA MIGLIORATA ---

                            if (gridDataForAnalysis.isEmpty()) {
                                Toast.makeText(context, context.getString(R.string.no_valid_rows_to_sync), Toast.LENGTH_SHORT).show()
                            } else {
                                databaseViewModel.analyzeGridData(gridDataForAnalysis)
                                Toast.makeText(context, context.getString(R.string.sync_analysis_started), Toast.LENGTH_SHORT).show()
                            }
                        }) {
                            // L'icona rimane la stessa
                            StatusIcon(
                                baseIcon = Icons.Default.Sync,
                                badgeType = when (syncStatus) {
                                    com.example.merchandisecontrolsplitview.data.SyncStatus.SYNCED_SUCCESSFULLY -> BadgeType.SUCCESS
                                    com.example.merchandisecontrolsplitview.data.SyncStatus.ATTEMPTED_WITH_ERRORS -> BadgeType.WARNING
                                    com.example.merchandisecontrolsplitview.data.SyncStatus.NOT_ATTEMPTED -> BadgeType.NONE
                                },
                                contentDescription = stringResource(R.string.sync_with_database)
                            )
                        }

                        // --- MODIFICA QUI: PULSANTE ESPORTA ---
                        IconButton(onClick = { saveLauncher.launch(entryId) }) {
                            // SOSTITUIAMO IL VECCHIO ROW CON IL NUOVO STATUSICON
                            IconButton(onClick = { saveLauncher.launch(entryId) }) {
                                StatusIcon(
                                    baseIcon = Icons.Default.FileDownload,
                                    // MODIFICA: Usa badgeType anche qui per coerenza
                                    badgeType = if (wasExported) BadgeType.SUCCESS else BadgeType.NONE,
                                    contentDescription = stringResource(R.string.export_file)
                                )
                            }
                        }
                    }
                }
            )
        }
    ) { paddingValues ->
        Box(
            Modifier
                .fillMaxSize()
                .padding(paddingValues)) {
            Column(Modifier.fillMaxSize()) {
                if (excelData.isNotEmpty()) {
                    val localizedHeader = excelData[0].map { getLocalizedHeader(context, it) }
                    val localizedData = listOf(localizedHeader) + excelData.drop(1)
                    ZoomableExcelGrid(
                        data = localizedData,
                        cellWidth = 120.dp,
                        cellHeight = 48.dp,
                        selectedColumns = excelViewModel.selectedColumns,
                        editableValues = editableValues,
                        completeStates = completeStates,
                        searchMatches = searchMatches,
                        errorRowIndexes = errorIndexes,
                        generated = true,
                        editMode = false,
                        onCompleteToggle = { row ->
                            completeStates[row] = !completeStates[row]
                            excelViewModel.updateHistoryEntry()
                        },
                        onCellEditRequest = { _, _ -> },
                        onQuantityCellClick = { r ->
                            infoRowIndex = r; infoDialogFocusField = 0; showInfoDialog = true
                        },
                        onPriceCellClick = { r ->
                            infoRowIndex = r; infoDialogFocusField = 1; showInfoDialog = true
                        },
                        onRowCellClick = { r ->
                            infoRowIndex = r; infoDialogFocusField = 0; showInfoDialog = true
                        },
                        onHeaderClick = { colIdx -> headerDialogIndex = colIdx }
                    )
                }
            }

            if (showExitDialog) {
                AlertDialog(
                    onDismissRequest = { showExitDialog = false },
                    title = { Text(stringResource(R.string.exit_confirmation_title))},
                    text = { Text(stringResource(R.string.exit_confirmation_message)) },
                    confirmButton = {
                        TextButton(
                            onClick = {
                                showExitDialog = false
                                onConfirmAction() // Esegue l'azione salvata (Indietro o Home)
                            }
                        ) {
                            Text(stringResource(R.string.exit))
                        }
                    },
                    dismissButton = {
                        TextButton(onClick = { showExitDialog = false }) {
                            Text(stringResource(R.string.cancel))
                        }
                    }
                )
            }

            // FAB Scanner e Cerca
            if (excelData.isNotEmpty() && generated) {
                Column(
                    Modifier.align(Alignment.BottomEnd).padding(end = 16.dp, bottom = 88.dp),
                    verticalArrangement = Arrangement.spacedBy(16.dp),
                    horizontalAlignment = Alignment.End
                ) {
                    FloatingActionButton(onClick = {
                        val opts = ScanOptions().apply {
                            setDesiredBarcodeFormats(ALL_CODE_TYPES)
                            setCaptureActivity(PortraitCaptureActivity::class.java)
                            setOrientationLocked(true)
                            setBeepEnabled(true)
                            setPrompt(context.getString(R.string.scan_prompt))
                        }
                        scanLauncher.launch(opts)
                    }) {
                        Icon(
                            Icons.Filled.CameraAlt,
                            contentDescription = stringResource(R.string.scan_icon_desc)
                        )
                    }

                    FloatingActionButton(onClick = { searchText = ""; showSearchDialog = true }) {
                        Icon(
                            Icons.Filled.Search,
                            contentDescription = stringResource(R.string.search_icon_desc)
                        )
                    }
                }
            }

            // Dialog di ricerca
            if (showSearchDialog) {
                AlertDialog(
                    onDismissRequest = {},
                    title = { Text(stringResource(R.string.search_number)) },
                    text = {
                        Column {
                            Button(onClick = {
                                scanLauncher.launch(
                                    ScanOptions().apply {
                                        setDesiredBarcodeFormats(ALL_CODE_TYPES)
                                        setCaptureActivity(PortraitCaptureActivity::class.java)
                                        setOrientationLocked(true)
                                        setBeepEnabled(true)
                                        setPrompt(context.getString(R.string.scan_prompt))
                                    }
                                )
                            }, Modifier.fillMaxWidth().padding(bottom = 8.dp)) {
                                Icon(Icons.Filled.CameraAlt, contentDescription = null)
                                Spacer(Modifier.width(8.dp))
                                Text(stringResource(R.string.scanner))
                            }
                            TextField(
                                value = searchText,
                                onValueChange = { searchText = it },
                                label = { Text(stringResource(R.string.insert_number)) },
                                singleLine = true,
                                keyboardOptions = KeyboardOptions(
                                    keyboardType = KeyboardType.Number,
                                    imeAction = ImeAction.Search
                                ),
                                keyboardActions = KeyboardActions(onSearch = { performSearch() }),
                                modifier = Modifier.fillMaxWidth()
                            )
                        }
                    },
                    confirmButton = {
                        TextButton(onClick = { performSearch() }) {
                            Text(
                                stringResource(R.string.search_number)
                            )
                        }
                    },
                    dismissButton = {
                        TextButton(onClick = { showSearchDialog = false }) {
                            Text(
                                stringResource(R.string.clear)
                            )
                        }
                    }
                )
            }

            if (showInfoDialog && infoRowIndex in excelData.indices) {

                val header = excelData.first()
                val row = excelData[infoRowIndex]
                val qtyReq = remember { FocusRequester() }
                val priceReq = remember { FocusRequester() }
                val backgroundFocusRequester = remember { FocusRequester() }
                LaunchedEffect(showInfoDialog, infoDialogFocusField) {
                    if (infoDialogFocusField == 0) qtyReq.requestFocus() else priceReq.requestFocus()
                }
                AlertDialog(
                    onDismissRequest = { showInfoDialog = false },
                    title = { Text(stringResource(R.string.row_info)) },
                    text = {
                        Column(
                            Modifier
                                .verticalScroll(rememberScrollState())
                                .fillMaxWidth()
                                .focusRequester(backgroundFocusRequester)
                                .focusable()
                                .clickable(
                                    indication = null,
                                    interactionSource = remember { MutableInteractionSource() }
                                ) {
                                    // 4. Richiedi il focus sullo sfondo
                                    backgroundFocusRequester.requestFocus()
                                }
                        ) {
                            header.forEachIndexed { ci, name ->
                                if (name != "complete") {
                                    when (name) {
                                        "realQuantity", "RetailPrice" -> {
                                            val idx = if (name == "realQuantity") 0 else 1
                                            val req = if (idx == 0) qtyReq else priceReq
                                            var tf by remember {
                                                mutableStateOf(
                                                    TextFieldValue(
                                                        editableValues[infoRowIndex][idx].value,
                                                        TextRange(editableValues[infoRowIndex][idx].value.length)
                                                    )
                                                )
                                            }
                                            Row(
                                                Modifier.fillMaxWidth().padding(vertical = 4.dp),
                                                verticalAlignment = Alignment.CenterVertically
                                            ) {
                                                Text(
                                                    "${getLocalizedHeader(context, name)}:",
                                                    Modifier.weight(1f),
                                                    style = MaterialTheme.typography.bodyMedium
                                                )
                                                TextField(
                                                    value = tf,
                                                    onValueChange = { nv ->
                                                        tf =
                                                            nv; editableValues[infoRowIndex][idx].value =
                                                        nv.text; excelViewModel.updateHistoryEntry()
                                                    },
                                                    singleLine = true,
                                                    keyboardOptions = KeyboardOptions(
                                                        keyboardType = KeyboardType.Number,
                                                        imeAction = if (idx == 0) ImeAction.Next else ImeAction.Done
                                                    ),
                                                    keyboardActions = KeyboardActions(
                                                        onNext = { if (idx == 0) priceReq.requestFocus() },
                                                        onDone = {
                                                            completeStates[infoRowIndex] =
                                                                !completeStates[infoRowIndex]; excelViewModel.updateHistoryEntry(); showInfoDialog =
                                                            false
                                                        }),
                                                    modifier = Modifier.weight(1f).height(48.dp)
                                                        .border(
                                                            1.dp,
                                                            Color.Gray,
                                                            RoundedCornerShape(4.dp)
                                                        ).clip(RoundedCornerShape(4.dp))
                                                        .focusRequester(req)
                                                )
                                            }
                                        }

                                        "purchasePrice" -> {
                                            val idx = header.indexOf("purchasePrice")
                                            val value = row.getOrNull(idx) ?: ""
                                            Row(
                                                Modifier.fillMaxWidth().padding(vertical = 4.dp),
                                                verticalAlignment = Alignment.CenterVertically
                                            ) {
                                                Text(
                                                    getLocalizedHeader(context, name) + ":",
                                                    Modifier.weight(1f),
                                                    style = MaterialTheme.typography.bodyMedium
                                                )
                                                Text(
                                                    value,
                                                    Modifier
                                                        .weight(1f)
                                                        .background(
                                                            MaterialTheme.colorScheme.surfaceVariant,
                                                            RoundedCornerShape(4.dp)
                                                        )
                                                        .padding(
                                                            horizontal = 8.dp,
                                                            vertical = 2.dp
                                                        ),
                                                    style = MaterialTheme.typography.bodyMedium.copy(
                                                        color = MaterialTheme.colorScheme.primary,
                                                        fontWeight = FontWeight.Bold
                                                    )
                                                )
                                                IconButton(
                                                    onClick = {
                                                        calcInput = value
                                                        calcRowIndex = infoRowIndex
                                                        showCalcDialog = true
                                                    }
                                                ) {
                                                    Icon(
                                                        Icons.Filled.Calculate,
                                                        contentDescription = stringResource(R.string.calculate_new_value)
                                                    )
                                                }
                                            }
                                        }

                                        else -> {
                                            Row(Modifier.fillMaxWidth().padding(vertical = 4.dp)) {
                                                Text(
                                                    getLocalizedHeader(context, name) + ":",
                                                    Modifier.weight(1f),
                                                    style = MaterialTheme.typography.bodyMedium
                                                )
                                                val value = row.getOrNull(ci) ?: ""
                                                if (name == "oldPurchasePrice" || name == "oldRetailPrice") {
                                                    Text(
                                                        value,
                                                        Modifier.weight(1f)
                                                            .background(
                                                                if (value.isNotBlank()) MaterialTheme.colorScheme.primary.copy(
                                                                    alpha = 0.10f
                                                                ) else Color.Transparent,
                                                                RoundedCornerShape(4.dp)
                                                            )
                                                            .padding(
                                                                horizontal = 8.dp,
                                                                vertical = 2.dp
                                                            ),
                                                        style = MaterialTheme.typography.bodyMedium.copy(
                                                            color = if (value.isNotBlank()) MaterialTheme.colorScheme.primary else MaterialTheme.colorScheme.onSurface,
                                                            fontWeight = if (value.isNotBlank()) FontWeight.Bold else FontWeight.Normal
                                                        )
                                                    )
                                                } else {
                                                    Text(
                                                        value,
                                                        Modifier.weight(1f),
                                                        style = MaterialTheme.typography.bodyMedium
                                                    )
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                            HorizontalDivider(modifier = Modifier.padding(vertical = 8.dp))
                        }
                    },
                    dismissButton = {
                        // Lasciamo questo vuoto perché gestiamo tutto nel confirmButton
                    },
                    confirmButton = {
                        Row(
                            modifier = Modifier.fillMaxWidth(),
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            // 1. Icona della calcolatrice a sinistra
                            IconButton(onClick = { showGenericCalcDialog = true }) {
                                Icon(
                                    imageVector = Icons.Filled.Calculate,
                                    contentDescription = stringResource(R.string.fast_calculator_desc)
                                )
                            }

                            // 2. Spacer flessibile che spinge tutto a destra
                            Spacer(Modifier.weight(1f))

                            // 3. Pulsante secondario "Confirmar" (per chiudere il dialogo)
                            TextButton(onClick = { showInfoDialog = false }) {
                                Text(stringResource(R.string.confirm)) // O il testo appropriato per "Chiudi"
                            }

                            // Aggiungiamo un piccolo spazio tra i pulsanti
                            Spacer(Modifier.width(8.dp))

                            // 4. Pulsante primario "Completo" con riempimento
                            Button(
                                onClick = {
                                    completeStates[infoRowIndex] = !completeStates[infoRowIndex]
                                    excelViewModel.updateHistoryEntry()
                                    showInfoDialog = false
                                }
                            ) {
                                Text(getLocalizedHeader(context, "complete"))
                            }
                        }
                    }

                )
            }

            if (showCalcDialog && calcRowIndex == infoRowIndex) {
                CalculatorDialog(
                    title = stringResource(R.string.calc_title),
                    value = calcInput,
                    onValueChange = { calcInput = it },
                    onResult = { res ->
                        // Aggiorna la cella della purchasePrice SOLO per questa riga
                        val idx = excelViewModel.excelData.first().indexOf("purchasePrice")
                        if (idx > -1) {
                            excelViewModel.excelData[infoRowIndex] =
                                excelViewModel.excelData[infoRowIndex].toMutableList()
                                    .also { it[idx] = formatDecimal(res) }
                            excelViewModel.updateHistoryEntry()
                        }
                    },
                    onDismiss = { showCalcDialog = false }
                )
            }
        }
    }

    // Dialog rinomina file
    if (showRenameDialog) {
        AlertDialog(
            onDismissRequest = { showRenameDialog = false },
            title = { Text(stringResource(R.string.rename_file)) },
            text = {
                OutlinedTextField(
                    value = renameText,
                    onValueChange = { renameText = it },
                    label = { Text(stringResource(R.string.new_name)) },
                    singleLine = true,
                    modifier = Modifier.fillMaxWidth()
                )
            },
            confirmButton = {
                TextButton(onClick = {
                    val entry = excelViewModel.historyEntries.find { it.id == entryId }
                    if (entry != null && renameText.isNotBlank()) {
                        excelViewModel.renameHistoryEntry(entry, renameText)
                        titleText = renameText
                        showRenameDialog = false
                    }
                }) {
                    Text(stringResource(R.string.confirm))
                }
            },
            dismissButton = {
                TextButton(onClick = { showRenameDialog = false }) {
                    Text(stringResource(R.string.cancel))
                }
            }
        )
    }

    if (showGenericCalcDialog) {
        var genericCalcInput by remember { mutableStateOf("") }
        CalculatorDialog(
            title = stringResource(R.string.generic_calculator_title),
            value = genericCalcInput,
            onValueChange = { genericCalcInput = it },
            // onResult è vuota o semplicemente chiude il dialogo. NON modifica i dati.
            onResult = { /* Non fa nulla con il risultato */ },
            onDismiss = { showGenericCalcDialog = false }
        )
    }

    // Dialog per la selezione del tipo di colonna
    if (showCustomHeaderDialog && headerDialogIndex != null) {
        AlertDialog(
            onDismissRequest = { showCustomHeaderDialog = false; customHeader = ""; headerDialogIndex = null },
            title = { Text(stringResource(R.string.custom_header_dialog_title)) },
            text = {
                OutlinedTextField(
                    value = customHeader, onValueChange = { customHeader = it },
                    label = { Text(stringResource(R.string.custom_header_label)) },
                    singleLine = true, modifier = Modifier.fillMaxWidth()
                )
            },
            confirmButton = {
                TextButton(onClick = {
                    val idx = headerDialogIndex!!
                    if (customHeader.isNotBlank()) {
                        excelViewModel.setHeaderType(idx, customHeader.trim())
                        showCustomHeaderDialog = false; customHeader = ""; headerDialogIndex = null
                    }
                }) { Text(stringResource(R.string.confirm)) }
            },
            dismissButton = { TextButton(onClick = { showCustomHeaderDialog = false; customHeader = "" }) { Text(stringResource(R.string.cancel)) } }
        )
    }

    headerDialogIndex?.let { colIdx ->
        AlertDialog(
            onDismissRequest = { headerDialogIndex = null },
            title = { Text(stringResource(R.string.select_column_type)) },
            text = {
                Column {
                    possibleKeys.forEach { key ->
                        TextButton(onClick = { excelViewModel.setHeaderType(colIdx, key); headerDialogIndex = null }) { Text(getLocalizedHeader(context, key)) }
                    }
                    TextButton(onClick = { showCustomHeaderDialog = true; headerDialogIndex = colIdx }) { Text(stringResource(R.string.custom_column_type)) }
                }
            },
            confirmButton = {},
            dismissButton = { TextButton(onClick = { headerDialogIndex = null }) { Text(stringResource(R.string.close)) } }
        )
    }

}


fun evalSimpleExpr(expr: String): Double {
    val clean = expr.replace(",", ".").replace(" ", "")
    return object : Any() {
        var pos = -1; var ch = 0
        fun nextChar() { ch = if (++pos < clean.length) clean[pos].code else -1 }
        fun eat(charToEat: Int): Boolean {
            while (ch == ' '.code) nextChar()
            if (ch == charToEat) { nextChar(); return true }
            return false
        }
        fun parse(): Double {
            nextChar()
            val x = parseExpression()
            if (pos < clean.length) throw RuntimeException("Unexpected: " + clean[pos])
            return x
        }
        fun parseExpression(): Double {
            var x = parseTerm()
            while (true) {
                when {
                    eat('+'.code) -> x += parseTerm()
                    eat('-'.code) -> x -= parseTerm()
                    else -> return x
                }
            }
        }
        fun parseTerm(): Double {
            var x = parseFactor()
            while (true) {
                when {
                    eat('*'.code) -> x *= parseFactor()
                    eat('/'.code) -> x /= parseFactor()
                    else -> return x
                }
            }
        }
        fun parseFactor(): Double {
            if (eat('+'.code)) return parseFactor()
            if (eat('-'.code)) return -parseFactor()
            val x: Double
            val startPos = pos
            if (eat('('.code)) {
                x = parseExpression()
                eat(')'.code)
            } else if ((ch in '0'.code..'9'.code) || ch == '.'.code) {
                while ((ch in '0'.code..'9'.code) || ch == '.'.code) nextChar()
                x = clean.substring(startPos, pos).toDouble()
            } else throw RuntimeException("Unexpected: " + ch.toChar())
            return x
        }
    }.parse()
}

@Composable
fun CalculatorDialog(
    title: String,
    value: String,
    onValueChange: (String) -> Unit,
    onResult: (String) -> Unit,
    onDismiss: () -> Unit
) {
    var input by remember { mutableStateOf(value) }
    var result by remember { mutableStateOf("") }

    val errorText = stringResource(R.string.error_label)

    fun updateResult(str: String) {
        result = try {
            if (str.trim().endsWith("=")) {
                evalSimpleExpr(str.trim().removeSuffix("=")).toString()
            } else ""
        } catch (_: Exception) { errorText }
    }

    AlertDialog(
        onDismissRequest = onDismiss,
        title = { Text(title) },
        text = {
            Column(
                horizontalAlignment = Alignment.CenterHorizontally,
                modifier = Modifier.fillMaxWidth()
            ) {
                OutlinedTextField(
                    value = input,
                    onValueChange = {
                        input = it
                        updateResult(it)
                        onValueChange(it)
                    },
                    label = { Text(stringResource(R.string.calc_label)) },
                    singleLine = true,
                    readOnly = true, // SOLO tramite tastiera custom
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(bottom = 6.dp)
                )
                // --- RISULTATO appena sotto il campo input ---
                val errorText = stringResource(R.string.error_label)
                Text(
                    text = if (result.isNotBlank() && result != errorText) {
                        stringResource(R.string.result) + " ${result.toDoubleOrNull()?.let { String.format(Locale.US, "%.2f", it) } ?: result}"
                    } else stringResource(R.string.result),
                    style = MaterialTheme.typography.titleMedium,
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(bottom = 24.dp)
                        .background(
                            MaterialTheme.colorScheme.primary.copy(alpha = 0.04f),
                            RoundedCornerShape(6.dp)
                        )
                        .padding(8.dp)
                )
                // --- PIÙ SPAZIO SOPRA LA TASTIERA ---
                Spacer(Modifier.height(8.dp))
                // --- TASTIERA con tasti più GRANDI e distanziati ---
                CalculatorKeyboard(
                    onKey = { key ->
                        when (key) {
                            "C" -> { input = ""; result = ""; onValueChange("") }
                            "<" -> {
                                if (input.isNotEmpty()) {
                                    input = input.dropLast(1)
                                    updateResult(input)
                                    onValueChange(input)
                                }
                            }
                            "=" -> {
                                if (input.isNotBlank()) {
                                    val toEval = if (input.trim().endsWith("=")) input.trim() else input.trim() + "="
                                    updateResult(toEval)
                                    input = toEval
                                    onValueChange(toEval)
                                }
                            }
                            else -> {
                                input += key
                                updateResult(input)
                                onValueChange(input)
                            }
                        }
                    },
                    buttonSize = 68.dp,    // <--- PIÙ GRANDE!
                    buttonFontSize = MaterialTheme.typography.headlineSmall.fontSize
                )
            }
        },
        confirmButton = {
            TextButton(onClick = {
                if (result.isNotBlank() && result != errorText) {
                    onResult(result)
                } else {
                    onResult(input)
                }
                onDismiss()
            }) { Text(stringResource(R.string.ok)) }
        },
        dismissButton = {
            TextButton(onClick = { onDismiss() }) { Text(stringResource(R.string.cancel)) }
        }
    )
}

@Composable
fun CalculatorKeyboard(
    onKey: (String) -> Unit,
    buttonSize: Dp = 56.dp,
    buttonFontSize: TextUnit = MaterialTheme.typography.titleLarge.fontSize
) {
    val buttons = listOf(
        listOf("C", "<"),
        listOf("+", "7", "8", "9"),
        listOf("-", "4", "5", "6"),
        listOf("*", "1", "2", "3"),
        listOf("/", ".", "0", "="),

    )
    Column(
        Modifier.fillMaxWidth(),
        horizontalAlignment = Alignment.CenterHorizontally
    ) {
        buttons.forEach { row ->
            Row(
                Modifier
                    .fillMaxWidth()
                    .padding(vertical = 2.dp), // più spazio tra righe
                horizontalArrangement = Arrangement.SpaceEvenly
            ) {
                row.forEach { label ->
                    Button(
                        onClick = { onKey(label) },
                        modifier = Modifier
                            .size(buttonSize)
                            .padding(2.dp),
                        shape = RoundedCornerShape(18.dp)
                    ) {
                        Text(label, fontWeight = FontWeight.Bold, fontSize = buttonFontSize)
                    }
                }
                // Per le righe più corte, aggiungi spaziatori
                repeat(4 - row.size) { Spacer(Modifier.size(buttonSize)) }
            }
        }
    }
}

@Composable
private fun StatusIcon(
    baseIcon: ImageVector,
    badgeType: BadgeType, // <-- Usa il nuovo enum invece di un Boolean
    contentDescription: String
) {
    Box {
        Icon(
            imageVector = baseIcon,
            contentDescription = contentDescription,
            modifier = Modifier.size(24.dp),
            tint = MaterialTheme.colorScheme.onSurfaceVariant
        )
        // Usa un when per decidere quale badge mostrare
        when (badgeType) {
            BadgeType.SUCCESS -> {
                Icon(
                    imageVector = Icons.Default.CheckCircle,
                    contentDescription = stringResource(R.string.status_completed),
                    modifier = Modifier
                        .size(12.dp)
                        .align(Alignment.TopEnd)
                        .offset(x = 4.dp, y = (-4).dp),
                    tint = Color(0xFF00C853) // Verde
                )
            }
            BadgeType.WARNING -> {
                Icon(
                    imageVector = Icons.Default.Error, // Icona di errore/avviso
                    contentDescription = stringResource(R.string.status_warning),
                    modifier = Modifier
                        .size(12.dp)
                        .align(Alignment.TopEnd)
                        .offset(x = 4.dp, y = (-4).dp),
                    tint = Color(0xFFFFA000) // Arancione/Ambra
                )
            }
            BadgeType.NONE -> { /* Non mostrare nulla */ }
        }
    }
}

fun formatDecimal(num: Double, digits: Int = 2): String =
    String.format(Locale.US, "%.${digits}f", num)

fun formatDecimal(num: String, digits: Int = 2): String =
    num.toDoubleOrNull()?.let { formatDecimal(it, digits) } ?: num